services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_PASSWORD: admin123
    ports:
      - "8000:8000"
      - "8089:8089"
    volumes:
      - ./app:/opt/splunk/etc/apps/splunk-baseline-application
